version: '3.8'

services:
  # Essential services only for development
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: 'rabbitmq-dev'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit mq_frame_max 131072
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  redis:
    image: 'redis:7-alpine'
    container_name: redis-dev
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: saad123
      MYSQL_DATABASE: starter
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3308:3306'
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'mysql-dev']
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
